version: '3'

services:
  mas_bort:
    image: annaspitsina/mas_bort:dev
    container_name: mas_bort
    privileged: true
    network_mode: "host"
    volumes:
      - ./:/workspace
    command: ["tail", "-f", "/dev/null"]
